### ISSUE TITLE
Ofrecer información estructurada de los horarios

### ISSUE THREAD

**Issue by virtor** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#1]
Actualmente en el campo horario se permite la introducción de texto libre, para que se pueda reutilizar sería necesario que la información estuviera más estructurada.

**Comment by ocorcho** [comment]
## Análisis sobre algunas alternativas posibles

Es importante tener en cuenta que no existe un estándar concreto para la especificación de horarios de apertura de lugares (comercios, equipamientos, etc.), por lo que la solución que se tome en este momento podría modificarse en el futuro si termina de surgir un estándar en este sentido. 
Algunas de las propuestas que se han hecho hasta el momento son las siguientes:
- https://schema.org/openingHours. Aquí se propone la utilización de textos para especificar los horarios de apertura de cualquier negocio (https://schema.org/LocalBusiness) o infraestructura (https://schema.org/CivicStructure). Estos textos utilizan los códigos Mo, Tu, We, Th, Fr, Sa, Su para referirse a los días de la semana, y los horarios de apertura y cierre separados por un guión. Por ejemplo: Tu,Th 16:00-20:00 para referirse a un local que abre de cuatro a ocho de la tarde los martes y jueves.
- Google Places API (https://developers.google.com/maps/documentation/javascript/places) especifica cómo se puede encontrar esta información para estos datos, con el atributo opening_hours, que contiene un array periods[] donde cada item es un day (número del 0 al 6) y time (de 0000 a 2359).
- FourSquare API (https://developer.foursquare.com/docs/responses/hours), que es similar a lo que se propone en Google Places API, con varios valores con el atributo days para especificar los días y open - start y open - end para especificar la hora de apertura y la de cierre.

También se puede considerar la propuesta, sencilla, de @jrub en su feedback sobre el uso de la API de Zaragoza (https://gist.github.com/jrub/8707031fb834d80a7828).

**Comment by ocorcho** [comment]
Propuesta que se puede considerar para la descripción de horarios, basada en el comentario anterior.

```
"openingHours": {
   "periods": [
     {"open": {"day": "Monday", "time": "09:00"}, 
      "close": {"day": "Monday", "time": "15:00"}},
     {"open": {"day": "Monday", "time": "17:00"}, 
      "close": {"day": "Monday", "time": "21:00"}},
     {"open": {"day": "Tuesday", "time": "10:00"}, 
      "close": {"day": "Tuesday", "time": "21:00"}},
      ...
}
```

**Comment by txtbits** [comment]
Teniendo en cuenta las diferentes propuestas y aportaciones hemos pensando en optar por la siguiente descripción de horarios:

``` json
{
    "openingHours": {
        "periods": [
            {
                "day": "Monday",
                "open": "09:00",
                "close": "15:00"
            },
            {
                "day": "Monday",
                "open": "17:00",
                "close": "19:00"
            },
            {
                "day": "Tuesday",
                "open": "10:00",
                "close": "21:00"
            }
        ]
    }
}
```

**Comment by jrub** [comment]
¿Esto dónde iría, dentro de cada `lugar`que devuelve el API?

También me surge la duda de la zona horaria. Durante el Hackaton ZgzAppStore nos pasó que el API devolvía un GMT y nosotros la considerábamos GMT+1.

**Comment by francho** [comment]
Yo pondría las horas en formato extendido indicando la zona horaria.

También se podría hacer en formato UTC y que luego cada cual se lo comparta a su zona horaria

**Comment by ocorcho** [comment]
Dentro de cada evento.
Incluir la zona horaria es buena idea, aunque curiosamente schema.org o APIs
como las de foursquare, google places, no lo especifican.

**Comment by jrub** [comment]
Supongo que no lo ponen porque pondrán UTC y luego cada cual adapta al usarla, creo que es buena opción.
Poner las horas en formato extendido como dice @francho también me parece mejor, el formato "18:00" casí parece algo para mostrar por pantalla, más que para consumir de un API.

**Comment by jrub** [comment]
Lo he estado pensando, y siendo que todo lo que ofrece el API es relativo siempre a la misma zona horaria, igual no hay que complicarlo más y dejarlo en el formato propuesto por @txtbits. Eso sí, actualmente algunas APIs devolvían GMT y otras GMT+1, si no recuerdo mal del Hackaton. Ese tipo de cosas, junto con la gestión del cambio a horario de verano (GMT+2) tiene que estar bien montado en el servidor. Si eso rula bien, creo que sería suficiente, ¿no?

**Comment by virtor** [comment]
La hora en GMT+1 se utiliza en los conjuntos de datos disponibles vía SOLR, porque es su forma de trabajar internamente con las fechas.

Es un tema que hemos tenido que explicar a diferentes personas por lo que creemos que es más fácil mostrar la hora local como indican en [Google Places](https://developers.google.com/places/webservice/details) en opening_hours -> periods, aunque sea más formal como propone @francho

**Comment by txtbits** [comment]
La información referente a los horarios queda de la siguiente manera:

``` json
"subEvent": [
  {
    "horario": "string",
    "comentarios": "string",
    "horaInicio": "string",
    "horaFinal": "string",
    "openingHours": [
      {
        "dia": "string",
        "horaApertura": "string",
        "horaCierre": "string"
      }
    ]
  }
],
```

A través del vector _OpeningHours_ se pueden establecer múltiples horarios de apertura/cierre haciendo diferentes combinaciones con el campo _día_:
- Todos los días
- Lunes
- Martes
- Miércoles
- Jueves
- Viernes
- Sábado
- Domingo
- Lunes a Viernes
- Fin de semana

Ejemplo de actividad:

``` json
{
    "id": 000000,
    "title": "Título de la actividad",
    "subEvent": [
        {
            "lugar": {
                ...
            },
            "horario": "Lunes de 9 a 10. Miércoles de 11 a 12. Viernes de 13 a 14h",
            "fechaInicio": "2015-10-02T00:00:00Z",
            "fechaFinal": "2015-10-23T00:00:00Z",
            "openingHours": [
                {
                    "dia": "Lunes",
                    "horaApertura": "09:00",
                    "horaCierre": "10:00"
                },
                {
                    "dia": "Miércoles",
                    "horaApertura": "11:00",
                    "horaCierre": "12:00"
                },
                {
                    "dia": "Viernes",
                    "horaApertura": "13:00",
                    "horaCierre": "14:00"
                }
            ]
        }
    ],
    ...
}
```

Se mantienen los campos _horario_ y _comentarios_ a nivel de _subEvent_ permitiendo la introducción de texto libre para aquellas actividades en las que exista algún dato especial referente al horario y para aquellas actividades en las que no se pueda establecer un horario estructurado.
