### ISSUE TITLE
[Swagger] La sección de Agenda Zaragoza se despliega de forma raruna

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#11]
Esto no tiene ninguna prioridad. Simplemente me ha hecho gracias que al acceder a la documentación   http://www.zaragoza.es/docs-api y clicar la "Agenda Zaragoza", se despliegan elementos entremezclados con el resto de endpoints... Adjunto captura de Google Chrome. Lo he testeado también en Safari y Firefox Developer Edition, y se replica.

![screenshot 2015-04-17 14 43 47](https://cloud.githubusercontent.com/assets/472092/7202202/6a3d81be-e510-11e4-9d1a-22c22b3aab05.png)

**Comment by jrub** [comment]
...creo que es cuestión de agrupar los tres seguidos, y fiesta

**Comment by virtor** [comment]
Es un problema con swagger, tenemos que actualizar la versión para ver si se soluciona el error.

**Comment by virtor** [comment]
Hemos actualizado la versión de swagger y ya debería estar solucionado.

**Comment by jrub** [comment]
No sólo está solucionado sino que queda bastante más limpio la lista de endpoints y tal :-)
