### ISSUE TITLE
[Swagger] El Model y Model Schema no aparece cuando son listas

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#12]
Ejemplo de Model con lista:
![screenshot 2015-04-17 14 49 42](https://cloud.githubusercontent.com/assets/472092/7202267/003ebf70-e511-11e4-8033-283a6fcb0158.png)

Ejemplo de ModelSchema con lista:
![screenshot 2015-04-17 14 48 57](https://cloud.githubusercontent.com/assets/472092/7202270/042292ba-e511-11e4-9262-07c716901b3b.png)

**Comment by jrub** [comment]
Además, hay alguno que es un objeto normal (no lista), y no debe estar bien anotado, como en las procesiones:

![screenshot 2015-04-17 14 52 45](https://cloud.githubusercontent.com/assets/472092/7202320/81a5bbc2-e511-11e4-9a4b-9764c2e4343a.png)

**Comment by virtor** [comment]
Hemos actualizado la versión de swagger y ya debería estar solucionado.

**Comment by jrub** [comment]
mmmm ahora me sale como un objeto simple, no como una lista... ¿Siempre ha sido así entonces y simplemente estaba mal marcado?

**Comment by virtor** [comment]
Corregido, ahora aparecen como listas
