### ISSUE TITLE
[SPARQL] devuelve la URI de descripción del recurso del API, en vez de la del evento "para humanos"

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#13]
Aquí se autoexplica: https://github.com/jrub/LaAgendica/commit/f201fc6d8e785c24634485ffc1d05218b5d35c6f

**Comment by jrub** [comment]
SPARQL devuelve:

```
 "uri": { "type": "uri", "value": "http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza/133269" }
```

Que es una URL que describe el API (es un documento técnico, no un texto enfocado al ciudadano)

**Comment by virtor** [comment]
Lo hemos modificado para que la uri http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza/{id} redirija al detalle del acto http://www.zaragoza.es/ciudad/actividades/ficha_Agenda?codigo={id}

**Comment by jrub** [comment]
Pero entonces, ya no se puede ver el detalle del API... :flushed: accediendo a la URL por el navegador también redirige...

**Comment by ocorcho** [comment]
A mí tampoco me gusta la solución, Víctor, puesto que lo interesante de tener las URIs de-referenciables es que se puede acceder a muy distintas vistas. @jrub ¿qué te parecería suficiente para poder acceder a esa información adecuadamente? Una opción es que se devolviera el seeAlso o schema:url (ahora mismo no recuerdo la propiedad que ofrecemos), que es el HTML bonito al que ahora mismo redirige @virtor

**Comment by jrub** [comment]
Esto es precisamente lo que comentaba en el Gist https://gist.github.com/jrub/8707031fb834d80a7828 cuando decía que haya coherencia entre las diferentes APIs. Con APIs me refiero al API REST, API SOLR y API SPARQL, lo aclaro puesto que soléis llamar "API" al API REST.

Las 3 APIs deben devolver lo mismo. En este caso, el campo `uri`, debe devolver siempre lo mismo si ataco al mismo recurso. Eso es lo importante.

Respecto a qué URI devolver, la descripción del API es una documentación para el "reutilizador" que está bien que exista, pero no le encuentro sentido devolverla como respuesta en ningún API (a no ser que fuera un API que describa las APIs, claro). Pero ahí estamos describiendo el recurso que representa a un evento.

**Comment by virtor** [comment]
La redirección la hemos puesto porque entendemos que cuando alguien accede a ver un recurso en formato HTML, le ofrecemos la salida en HTML de dicho recurso. Si se quieren ver los detalles del api rest, es mejor pedir el recurso en el formato con el que se va a trabajar porque por ejemplo, la estructura en jsonld es diferente a la estructura en json. La salida en HTML de api fue pensada para poder ver los datos en bruto cuando no haya una alternativa HTML en www.zaragoza.es.

Respecto a la coherencia entre las 3 apis, es complicado porque como ya comentamos son tecnologías diferentes cada una con sus peculiaridades y sintaxis, por eso en lo que estamos trabajando es en que la información esté disponible en las tres apis para que el reutilizador consuma la que prefiera.

**Comment by jrub** [comment]
Me refiero a que el mismo campo sea igual en todas las APIs. En concreto, `uri`, que cambia su contenido, en REST es una URI que describe el recurso (un evento), mientras que en SPARQL describe un endpoint del API... no he entendido muy bien a qué te refieres en el primer párrafo, no digo nada de formatos, y tampoco de las peculiaridades del API, con su "type" y "value" en el caso de SPARQL...

No sé si realmente me estoy explicando bien :-/

**Comment by jrub** [comment]
Adjunto este paper del W3C en el que claramente especifica que se deben evitar los redirects en apps móviles http://www.w3.org/TR/mwabp/#bp-redirect-minimize

**Comment by virtor** [comment]
Centrando un poco el tema creo que hay que distinguir dos cosas:
- Unificar los atributos que se sirven desde API, SOLR y SPARQL, esto, como ya dije, no puede ser porque son tecnologías diferentes.
- Evitar los redirects. Desde una aplicación que consume los datos, sólo se hace uso del redirect para enlazar a la fuente de información oficial, para lo demás se consumen los datos en el formato que se desee. De todas formas hemos añadido en la agenda el atributo rdf:Alt para indicar la url en www.zaragoza.es, también se puede utilizar para cerrar el issue #22 mientras adecuamos la visualización.

PD. En Mobile Web Best Practices 1.0 del W3C http://www.w3.org/TR/mobile-bp/#d0e959 dice que se pueden usar los redirects, como mucho uno :-)

**Comment by jrub** [comment]
Ok. Una pregunta, ¿dónde puede mirarse que ahora existe ese campo? La documentación de SPARQL son un montón de vocabularios largos de leer... ¿existe algún resumen como los campos indizados del SOLR? http://www.zaragoza.es/ciudad/risp/camposindizados.htm#agenda

Ah, y ¿podrías explicar mejor cómo puede usarse esto para cerrar el issue #22 ? No he entendido la relación.

Gracias

**Comment by virtor** [comment]
No existe ningún resumen, aparte del vocabulario http://vocab.linkeddata.es/datosabiertos/def/cultura-ocio/agenda-content/0.1/index.html

Puedes obtener los atributos asociados aun objeto ejecutando la siguiente consulta:
`select distinct ?uri 
where  {
    ?uriCont a <http://schema.org/Event>;
    ?uri ?obj.
}`

Sobre el issue #22 me refiero a que los errores 404 que daban eventos se solucionarían si en vez de apuntar a la uri del api, apuntais a la uri del atributo alt.
