### ISSUE TITLE
[SOLR] indexar campo "destacada" permitiría filtrar por él

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#14]
_Estaría bien indexar en SOLR el campo `destacada`, para que todos los APIs tengan más o menos lo mismo._

Como sabéis, en LaAgendica empezamos [atacando el endpoint SOLR](https://github.com/jrub/LaAgendica/blob/master/www/js/controllers.js#L130), pero tuvimos que añadir [peticiones al endpoint SPARQL](https://github.com/jrub/LaAgendica/blob/master/www/js/controllers.js#L22) porque no se puede filtrar el SOLR por `destacada` (eventos destacados).

Es decir, tenemos una sección de Destacados que sacamos por SPARQL, y el resto de secciones las sacamos por SOLR. Me gustaría poder usar un simple filtro de Angular para situar los eventos destacados de esa sección arriba del todo de esa sección, y pintarlos diferente. Obviamente podría pasarme a utilizar exclusivamente SPARQL, pero como digo creo que estaría bien dar coherencia entre las APIs, evitando limitaciones en unos (SOLR en este caso) siendo que se puede mejorar fácil (¿sólo es reindexar, no? igual tiene más tela y no soy consciente de ello). Además me gusta atacar a las dos APIs, porque los mando como ejemplo de uso (además de los vuestros).

**Comment by virtor** [comment]
Añadido campo _destacada_b_ y _diasHastaFinalizacion_i_
