### ISSUE TITLE
Coherencia entre IDs de SOLR y SPARQL

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#15]
SOLR devuelve los IDs de evento en formato:
`"id": "acto-117081",``

SPARQL devuelve los IDs:
`"id": "117081",`

Sugiero utilizar exactamente el mismo ID (el de sólo el número, como integer) para que los reutilizadores no tengamos que parsear a mano las cosas si usamos en la misma aplicación ambos APIs.

¡Gracias, saludos!

**Comment by virtor** [comment]
En SOLR los registros deben tener un identificador, como además de actividades se almacenan otras cosas, para distinguirlas y no repetir identificadores (ya que puede existir un equipamiento con id=1234 y que a su ve exista un acto con id=1234) decidimos añadir un prefijo para diferenciarlos.

**Comment by jrub** [comment]
¿y se puede procesar ese ID interno antes de devolverlo por el API?

**Comment by virtor** [comment]
En API ese ID Interno no se utiliza, sólo se utiliza en SOLR y desde allí no se puede procesar porque se publica directamente el índice.

**Comment by jrub** [comment]
Al menos documentarlo en http://www.zaragoza.es/ciudad/risp/camposindizados.htm#agenda ...

**Comment by jrub** [comment]
@virtor de lo que comentabas el 20 abril... ¿equipamiento y evento se persisten como si fueran la misma cosa, compartiendo IDs? 😳

**Comment by virtor** [comment]
No comparten ids porque añadimos el prefijo para distinguirlos, el acto 1234 se guarda en solr con el id=acto-1234 y el equipamiento 1234 se guarda en solr con id=recurso-1234
