### ISSUE TITLE
[Agenda Actividades] Documentar ejemplos para obtener los eventos de fiestas locales

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#16]
Molaría tener documentados ejemplos de cómo obtener los eventos de las Fiestas Locales ( http://www.zaragoza.es/ciudad/actividades/fiestas_locales/default.htm )

**Comment by txtbits** [comment]
Hemos normalizado y establecido un criterio único para la búsqueda de actividades relacionadas con Fiestas Locales.
En el portal de Fiestas Locales: http://www.zaragoza.es/ciudad/actividades/fiestas_locales/default.htm están indicadas las diferentes posibilidades, su título coincide con valor a buscar a través del campo "Programa" en los diferentes servicios (API, Solr, SPARQL).

Estas serían las opciones disponibles:
San Valero, Carnaval, Cincomarzada


San Jorge


Semana Santa


Verano

Fiestas del Pilar

Navidad

Se ha documentado en el apartado [Agenda del catálogo de conjuntos de datos](http://www.zaragoza.es/ciudad/risp/detalle_Risp?id=282), así como se han puesto un par de ejemplos en el [repositorio de github] (https://github.com/zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io).

**Comment by txtbits** [comment]
Hemos normalizado y establecido un criterio único para la búsqueda de actividades relacionadas con Fiestas Locales.
En el portal de Fiestas Locales: http://www.zaragoza.es/ciudad/actividades/fiestas_locales/default.htm están indicadas las diferentes posibilidades, su título coincide con valor a buscar a través del campo "Programa" en los diferentes servicios (API, Solr, SPARQL).

Estas serían las opciones disponibles actualmente:
- San Valero
- Carnaval
- Cincomarzada
- San Jorge
- Semana Santa
- Verano
- Fiestas del Pilar
- Navidad

Se ha documentado en el apartado [Agenda del catálogo de conjuntos de datos](http://www.zaragoza.es/ciudad/risp/detalle_Risp?id=282), y se han añadido un par de ejemplos en el [repositorio de github](https://github.com/zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io).

**Comment by jrub** [comment]
Mola :+1: 

Por cierto, ¿podríais linkar los ejemplos concretos? o os referís a la línea `http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza.json?q=programa==Verano` que sale al final de http://www.zaragoza.es/ciudad/risp/detalle_Risp?id=282

**Comment by txtbits** [comment]
Si, en el caso de API, utilizando ese ejemplo, puedes sustituir el valor de programa "Verano" por cualquier otra fiesta local de las que aparecen en el portal y te devolverá las actividades asociadas que estén **vigentes** el momento de la consulta.

Ejemplos: 
- `http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza.json?q=programa==Fiestas del Pilar`
- `http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza.json?q=programa==Carnaval`

El listado de fiestas locales podría incrementarse en el futuro por lo que se incluirían como nuevas categorías en el portal de [fiestas locales](http://www.zaragoza.es/ciudad/actividades/fiestas_locales/default.htm).
