### ISSUE TITLE
[procesiones] incluir fecha y hora completa

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#17]
Para facilitar el filtrado de procesiones por día, sería útil tener el `DateTime` de la procesión en la llamada a `/recurso/cultura-ocio/procesion`.

Ejemplo:
- endpoint: http://www.zaragoza.es/docs-api/#!/procesion
- response:

```
    {
      "id": 32,
      "dia": "Jueves Santo",
      "title": "Vía Crucis",
      "cofradia": "Cofradía de la Coronación de Espinas",
      "hora": "12:00 ",
      "salida": "Iglesia de San Felipe y Santiago (plaza de San Felipe)",
      "description": "Iglesia de San Felipe, Plaza de San Felipe, Gil Berges, Fuenclara, Alfonso I, Santa Isabel, Plaza del Justicia (13,15 horas), Manifestación, Alfonso I (13,30 horas), Plaza de Nuestra Señora del Pilar (lado de los Juzgados, cruzar a la altura de la calle Milagro de Calanda), Plaza del Pilar (lado Ayuntamiento), Plaza de la Seo, Catedral de la Seo del Salvador a las 15,00 horas.",
      "image": "http://www.zaragoza.es/cont/paginas/turismo/es/semanasanta/cofradias/comics/corJMju.jpg",
      "ruta_23030": "http://www.zaragoza.es/contenidos/semanasanta/31.json",
      "ruta_wgs84": "http://www.zaragoza.es/contenidos/semanasanta/4326/31.json"
    },
```

Ahora lo único que hay para filtrar es `dia`, que es un String. Sugiero añadir algo como: `"time": "1234567890"`siendo ese número los milliseconds desde 1970 (unixtime) o algo rollo [2012-04-23T18:25:43.511Z](http://stackoverflow.com/a/15952652/322168)

Así se podría evitar tener que "harcodear" esos Strings que devuelve el API para poder aplicar filtros, como en [este ejemplo](https://github.com/jrub/LaAgendica/blob/master/www%2Fjs%2Fapp.js#L45) de LaAgendica.

**Comment by virtor** [comment]
Hemos añadido el atributo fecha para cada una de las procesiones

**Comment by jrub** [comment]
¡Perfecto! :+1: 

Sobre todo si para las próximas Semanas Santas es como en el ejemplo del Swagger:  `"fecha": "2015-07-31T11:19:59Z",` es decir con la hora concreta (veo que para la SS pasada de este año sale `"fecha": "2015-04-02T00:00:00Z",``).

Si es así y lleva la hora, ¿cómo está el tema de la zona horaria? llevará una estándar rollo UTC, o la de ese momento en España (GMT+1/GMT+2)

**Comment by virtor** [comment]
En el próximo despliegue añadiremos la hora de ese momento en España
