### ISSUE TITLE
[Agenda Actividades] Uso de 'description' vs. 'description_t'

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#18]
Como comentaba en https://gist.github.com/jrub/8707031fb834d80a7828#comment-1429141, en LaAgendica usamos el campo `description_t` porque nos pareció el más completo. El caso es que `description_t` a veces incluye información del horario y/o lugar, y a veces no...

Según he ido aprendiendo de conversaciones con @virtor sobre las APIs de Datos Abiertos del Ayuntamiento:

> El campo description es la unión del contenido de dos atributos, description_t y lugar_t.
> A su vez lugar_t es la unión de nombrelugar_t direccionlugar_t y telefonolugar_t

Si realmente `description_t` es la concatenación de `description` con otros campos, yo ni los devolvería, sólo dificulta la compresión. Otra opción menos radical `;-)`es al menos documentar esto claramente.

Thanks!

**Comment by virtor** [comment]
Añadida explicación de los campos en http://www.zaragoza.es/ciudad/risp/camposindizados.htm#agenda
