### ISSUE TITLE
[API REST] El API REST ha dejado de devolver el campo 'uri'

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#20]
Las otras APIs sí lo devuelven. Sería recomendable tenerlo para poder linkar a la fuente de la información (la web del Ayto).

**Comment by jrub** [comment]
Dado que hace meses lo devolvía, más que tiparla como enhancement, la pondría como bug de tipo regresión

**Comment by virtor** [comment]
Hemos añadido el atributo rdf:Alt como se explica en #13

**Comment by jrub** [comment]
Gracias. Veo que además se ha documentado en el Swagger... Siento ser tan tiquismiquis, pero, creo que habría que, o bien darle un nombre más explicativo (alt-uri?), o bien documentar qué es 'alt'.

Me pongo en el lugar de un desarrollador que vaya a usar el API por primera vez y no me parece intuitivo el nombre, ni veo que esté explicado que ese string es una uri en ningún lugar...
