### ISSUE TITLE
Peso de las imágenes: no usable en Apps

### ISSUE THREAD

**Issue by jrub** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#25]
![screen shot 2015-10-12 at 18 07 37](https://cloud.githubusercontent.com/assets/472092/10432625/ac7c2354-710c-11e5-81ab-c8f48dae78b2.png)

Adjunto una captura de 20 imágenes de eventos ordenadas por peso, correspondiente a una petición de la sección "Qué hacer hoy" de LaAgendica. Para una app, las imágenes deberían escalarse en el servidor, y ofrecer diferentes tamaños para por ejemplo una lista con sus thumbnails, o una vista de detalle, como sugerimos en el issue #3 

Pero aquí vemos imágenes de hasta 3.5 Mb. Creo que nadie recomienda esos pesos, ni siquiera para navegador de escritorio. Todos sabemos que Facebook no sirve las fotos a su resolución completa, por ejemplo.

Por poner ejemplos concretos, una carga de la sección de "Qué hacer hoy" de LaAgendica, y recorrer toda la lista (las imágenes sólo se cargan al ir a visualizarlas), supone 31 MB y 1.2 minutos, según el debugger. Esto es una locura para una app móvil, ¡estamos hablando de una sóla carga de una de las secciones! Personalmente uso apps en Android en las que, según el resumen de uso de datos, gasto más o menos eso... al mes.

En mi opinión es imperativo buscar una solución. O bien escalar las imágenes en el servidor al servirlas, o bien obligar a que los que dan de alta los eventos tengan restricciones en el tamaño de las fotos (o bien el propio formulario de subida de fotos las escala a la hora de subirlas). Sin una solución al tema del peso de las imágenes, me empiezo a temer, ahora que he podido analizar el uso y consumo de una App tirando directamente de vuestras fuentes de datos, que actualmente no es viable su uso en Apps.  😓

**Comment by jrub** [comment]
No sólo es por el tema del consumo de datos, es también un problema de rendimiento, que no lo comenté. Por ejmplo, ahora mismo el scroll en cualquier lista de LaAgendica con imágenes da pena, y es normal, si tiene que mover una sóla imagen de 3,5 mb escalada a un huevo de 80x80, ya va a ir mal...

**Comment by virtor** [comment]
Hemos redimensionado las imágenes en jpg existentes y desplegado el cambio para que desde la gestión también se redimensionen.

**Comment by jrub** [comment]
¡Muchas gracias :ok_hand: ! La App ahora parece otra cosa, el subidón de rendimiento ha sido brutal. La carga inicial es casi instantánea, y el scroll bastante más ligero. Por cierto, ¿habéis mejorado también el rendimiento del SPARQL? Porque antes la media de respuesta de nuestra petición para eventos de Hoy era de entre 2-3 segundos, y ahora está alrededor del segundo :-)

¿Cómo veis el tema de implementar el issue #3 ? Sería una solución más buena, ya que aunque el escalado que habéis hecho está muy bien, he visto unas pocas imágenes (minoría) que ahora en la vista de detalle salen pixeladas. Aún así prefiero esto a la situación anterior, al menos para una App, por el tema de rendimiento y consumo de datos, pero molaría que siguiérais mejorando hacia la solución del issue #3, y en todas las APIs ;-)

¡Enhorabuena por resolverlo tan rápido, me he llevado una grata sorpresa esta mañana! :+1:
