### ISSUE TITLE
¿por qué la consulta de detalle de contratos devuelve duplicados?

### ISSUE THREAD

**Issue by richhl** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#29]
https://github.com/zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io/blob/master/sparql/queries/perfil-contratante/Detalle_Completo.sparql

Para reproducirlo basta ejecutarla desde el punto sparql 
http://www.zaragoza.es/ciudad/risp/sparql.htm

gracias!

**Comment by ocorcho** [comment]
Se trata de un error que tenemos identificado en la versión develop del triple store Virtuoso (7.00.3203) que hay ahora mismo en producción, y que esperamos cambiar en breve por una versión más estable en la que hemos comprobado que este error no se produce. 

Copio a @ma-garcia para que compruebe que este error se resuelve una vez que se despliegue la nueva versión.

**Comment by richhl** [comment]
gracias! algún workaround en el entretanto? se puede atacar al grafo directamente desde otros servicios que tengan otra versión de virtuoso como http://demo.openlinksw.com/sparql/ ? perdonad la pregunta de sparql newbie si no aplica.

salud

**Comment by ocorcho** [comment]
Como ese endpoint se basa en el que está instalado, no es posible. 
Una opción para reducir el número de duplicados (ojo, que esto es por diseño de SPARQL, al tener varios rdf:type los contratos) es eliminar el ?type del SELECT. Aún así, siguen saliendo algunos duplicados que no debieran salir, por el bug que he comentado antes.

**Comment by virtor** [comment]
Hemos modificado la consulta y algunas tripletas para que no aparezcan elementos duplicados.
