### ISSUE TITLE
Ayuda para crear una nueva consulta SPARQL para concurrencia de PYME's

### ISSUE THREAD

**Issue by richhl** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#30]
Hola, voy a intentar crear una nueva consulta que os contribuiré pero soy novato con SPARQL y con PPROC así que me costará, no sé si podéis echar una mano, lo que quisiera es generar una consulta que tenga el objeto de mostrar contratos de interés para PYMES o mejor microPYMES que sea de importes para los que pueden acreditar solvencia económica y que haya tiempo suficiente para preparar la oferta. podría ser algo como:

-Url de contratos licitados no adjudicados cuya fecha y hora límite de presentación de ofertas sea mayor de una dada, cuyo presupuesto se encuentre en un determinado rango de importes y cuyo objeto sea el de un conjunto de CPVs.

gracias

**Comment by richhl** [comment]
ummmm ¿no hay contratos vivos en el punto SPARQL?, esta consulta para fechas límite de licitación posteriores al día de hoy no devuelve ningún resultado:

```
PREFIX pproc: <http://contsem.unizar.es/def/sector-publico/pproc#>

select ?contrato ?fecha_limite where {
  ?contrato a pproc:Contract;
                   pproc:contractProcedureSpecifications ?procedimiento.
  ?procedimiento pproc:tenderDeadline ?fecha_limite
  FILTER (?fecha_limite >= now())
} 
ORDER BY DESC (?fecha_limite)
LIMIT 100
```

sin embargo si ponemos la fecha límite <now() obtenemos resultados:

| contrato | fecha_limite |
| --- | --- |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/67842-15 | 2015-11-17T13:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/69152-15 | 2015-11-17T13:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/68890-15 | 2015-11-16T13:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/68235-15 | 2015-11-11T13:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/68356-15 | 2015-11-11T13:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/68085-15 | 2015-11-11T13:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/68231-15 | 2015-11-11T13:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/65797-15 | 2015-11-11T00:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/66956-15 | 2015-11-10T00:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/67692-15 | 2015-11-06T13:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/63253-15 | 2015-11-04T00:00:00+01:00 |
| http://www.zaragoza.es/api/recurso/sector-publico/contrato/63255-15 | 2015-11-04T00:00:00+01:00 |

y si uno entra en el perfil del contratante ve que si que hay contratos vivos con fecha de licitación mayor que el día de hoy. http://www.zaragoza.es/ciudad/gestionmunicipal/contratos/

**Comment by ocorcho** [comment]
Esto seguramente lo tenga que revisar @virtor o @laurafl , porque no sé si ahora mismo se cargan también los que están en fase de licitación o se hace la carga cuando están ya adjudicados.

**Comment by richhl** [comment]
uff agradecería que me diéseis información porque si no hay anuncios en realidad queda invalidado el punto SQL para servicios de concurrencia de PYMES. La única forma sería hacer web scrapping del perfil de contratante con la inestabilidad que eso conlleva.

voy a probar el de la diputación de huesca.

**Comment by richhl** [comment]
huesca parece que ni anuncios ni contratos adjudicados volcados desde 2014, para reproducir lanzar la consulta contra el punto sparql de la diputación y obtenemos:

| contrato | fecha_limite |
| --- | --- |
| http://www.dphuesca.es/rdf/Contract/335 | Nueve meses |
| http://www.dphuesca.es/rdf/Contract/471 | Mañana |
| http://www.dphuesca.es/rdf/Contract/181 | Lunes, 26 de noviembre de 2007 |
| http://www.dphuesca.es/rdf/Contract/136 | Lunes, 2 de abril de 2007. |
| http://www.dphuesca.es/rdf/Contract/182 | Lunes 26 de noviembre de 2007 |
| http://www.dphuesca.es/rdf/Contract/561 | El plazo de presentación será de 10 días naturales a contar del siguiente a la publicación en el perfil de contratante de la Diputación, siendo el 1 de marzo de 2010. |
| http://www.dphuesca.es/rdf/Contract/50055 | 7 de mayo |
| http://www.dphuesca.es/rdf/Contract/316 | 60 días naturales |
| http://www.dphuesca.es/rdf/Contract/50009 | 5 de julio |
| http://www.dphuesca.es/rdf/Contract/50198 | 2014-09-01T23:59:00 |
| http://www.dphuesca.es/rdf/Contract/50194 | 2014-08-25T23:59:00 |

**Comment by laurafl** [comment]
Si, ya hemos notificado el fallo al servicio de contratación y esperamos tenerlo solucionado a la semana que viene (contratos por procedimiento abierto y negociados con publicidad). Si vuelves a lanzar la consulta que habías preparado debería salirte un contrato menor que se acaba de publicar, los contratos menores si que funcionan correctamente.

En cuanto a tu propuesta de filtrar por cpv, en los contratos menores de momento no es un campo obligatorio por lo que no siempre te funcionará. Estamos trabajando para integrarlo en su gestión.

**Comment by richhl** [comment]
gracias mil @laurafl comprobado que aparece el menor!

**Comment by richhl** [comment]
@laurafl ya he visto que en el menor y en los que no tienen definido CPV sale contenido http://purl.org/cpv/2008/code-    .dos preguntas:
1. ¿existe algún modo sea por existir algún término en PPROC que sirva al efecto o por alguna práctica específica de zaragoza que sirva para discriminar por objeto de contrato aunque no se disponga del mainObject en el contrato no armonizado? Obviamente es importante para que una empresa de limpieza o de informática pueda recibir información pertinente. ¿búsqueda regex en el título del contrato? ¿otros?
2. tenéis algún timing para poder tener CPVs en menores?

gracias de antemano.

**Comment by ocorcho** [comment]
Taggeo a @gesteban para que vea el comentario de la Diputación de Huesca, pues él ha sido quien ha realizado ese volcado de contratos.

**Comment by richhl** [comment]
vale ya la tengo puede mejorarse pero da juego. os la contribuyo por un PR. La podéis ver jugando en basil aquí: http://basil.kmi.open.ac.uk/app/#/basil/1jeiqtve8jpsx

**Comment by gesteban** [comment]
respecto a los contratos de la diputación de huesca, yo colaboré con ellos el año pasado durante la fase de mapeado desde la bbdd para generar las tripletas, pero del normalizado y el posterior mantenimiento no sé nada

en todo caso se tendría que contactar directamente con su servicio técnico

**Comment by ocorcho** [comment]
@gesteban ¿Puedes darnos los contactos para ver si van a continuar cargando contratos? Es muy importante conocer el SLA (Service Level Agreement) en cualquier iniciativa de datos abiertos, puesto que si no se actualizan es mejor decir explícitamente que no se están actualizando.

**Comment by gesteban** [comment]
la responsable durante la implantación era Cristina de la Hera (cdelahera@dphuesca.es)

si no contestase se puede probar a contactar con Javier Casado (jcasado@dphuesca.es), que es el técnico de desarrollo de la DPH
