### ISSUE TITLE
Falla una petición al API de la agenda

### ISSUE THREAD

**Issue by danilat** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#38]
Me he dado cuenta que las peticiones a http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza.json llevan un par de días fallando, por si acaso he entrado a http://www.zaragoza.es/docs-api/#!/Agenda_Zaragoza/get_recurso_cultura_ocio_evento_zaragoza por si había cambiado algo y veo que desde ahí también da errores

> {
> error: "Parametros incorrectos"
> }

**Comment by txtbits** [comment]
Hola, lo estamos revisando. Gracias por avisarnos.

**Comment by txtbits** [comment]
Buenos días, ya está solucionado.

**Comment by danilat** [comment]
Muchas gracias @txtbits! :smile:
