### ISSUE TITLE
Error al recuperar algunos cientos de filas en la agenda

### ISSUE THREAD

**Issue by danilat** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#39]
Parece que hay algunos datos corruptos o algo en la agenda

Por alguna razón al lanzar peticiones como:

`curl -X GET --header "Accept: application/json" "http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza?rf=html&results_only=false&srsname=wgs84&rows=500"`

Me devuelve esta respuesta:

```
{
  "error": "No row with the given identifier exists: [es.actividades.agenda.entidades.Entidad#13199]"
}
```

O esta otra:

`curl -X GET --header "Accept: application/json" "http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza?rf=html&results_only=false&srsname=wgs84&rows=3000"`

```
{
  "error": "Null value was assigned to a property of primitive type setter of es.actividades.agenda.entidades.Precio.hasCurrencyValue"
}
```

**Comment by txtbits** [comment]
Buenos días,

Ya está solucionado.

Saludos
