### ISSUE TITLE
Endpoint transporte urbano / poste no funciona

### ISSUE THREAD

**Issue by gimenete** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#40]
Hola, soy desarrollador de DNDzgz y estamos migrando partes de nuestra app que todavía hacían scrapping de las webs de urbanosdezaragoza, bizi, etc.

Tengo un problema con el endpoint:

```
GET /recurso/urbanismo-infraestructuras/transporte-urbano/poste/{id}
```

Devuelve

```
{
  "error": "Metodo no encontrado"
}
```

He probado con varios ids de poste obtenidos de otros enpoints. Todos con el mismo resultado.

Gracias.

**Comment by ocorcho** [comment]
Acabo de probar algunas de las llamadas y parece que funcionan:

```
http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/poste/tuzsa-798
```

y para sacar todos:

```
http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/poste
```

Eso sí, lo que puede ocurrir es que no coincidan los ids que se utilizan aquí con los ids que has obtenido de algún otro endpoint. Quizás es útil si pones algún ejemplo de los ids que estás utilizando y de dónde han salido, para ver cómo homogeneizarlos.

**Comment by gimenete** [comment]
Gracias por la rapidez en la respuesta :)

Si uso el endpoint que me da los postes de una línea:

```
curl -X GET --header "Accept: application/json" "http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/linea/32?rf=html&results_only=false&srsname=utm30n"
```

Me da por cada poste:

```
{
      "link": "http://www.urbanosdezaragoza.es/frm_esquemaparadatime.php?poste=208&direccion=AV REAL ZARAGOZA 65",
      "title": "Parada AV REAL ZARAGOZA 65",
      "description": "Poste 208",
      "geometry": {
        "type": "Point",
        "coordinates": [
          681244,
          4615079
        ]
      }
    }
```

De ahí estoy sacando el `poste=208` de la URL del link porque no hay campo id. Sería seguro añadir `tuzsa-` como prefijo siempre? O, podríais poner un id en los resultados de postes de este endpoint?

PD: Ahora veo que hay otro endpoint que sí da ids, pero no puedo relacionar los postes directamente con una línea de tuzsa sin tener que complicar el código:

```
http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/poste?rf=html&results_only=false&srsname=wgs84
```

Gracias!

**Comment by gimenete** [comment]
Para añadir más información, necesitaríamos que también el usuario pudiera obtener información de un poste escribiendo directamente el número de poste. Así por ejemplo ahora si el usuario está en el poste 55, escribe 55 en la app y nosotros parseamos esta URL: `http://www.urbanosdezaragoza.es/frm_esquemaparadatime.php?poste=55`

Sin embargo con el endpoint de la API OpenData he probado también con `tuzsa-xxx`y obtengo el mismo error puesto que los ids no coinciden:

```
curl "http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/poste/tusza-55.json?rf=html&srsname=wgs84"
```

**Comment by virtor** [comment]
Hay dos tipos de postes, los de urbanos de zaragoza que llevan el prefijo `tuzsa` y los de líneas de barrios rurales que llevan el prefijo `rural`.

En teoría, los que tienen URL de www.urbanosdezaragoza.es se deberían poder invocar como comentas desde el API Zaragoza, es decir:

Para obtener los datos del poste 55

```
http://www.urbanosdezaragoza.es/frm_esquemaparadatime.php?poste=55
```

La llamada al API Zaragoza debe ser:

```
http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/poste/tuzsa-55.json?rf=html&srsname=wgs84
```

(Creo que te daba error porque en vez de **tuzsa** ponías **tusza**) si te sigue dando problemas nos lo dices, aunque añadiremos en los datos de la línea el enlace con los datos de su poste para facilitar su integración con el api.

De forma que al pedir

```
http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/linea/32
```

La respuesta sería de este estilo:

```
{
      "about:": "http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/poste/tuzsa-55",
      "link": "http://www.urbanosdezaragoza.es/frm_esquemaparadatime.php?poste=208&direccion=AV REAL ZARAGOZA 65",
      "title": "Parada AV REAL ZARAGOZA 65",
      "description": "Poste 208",
      "geometry": {
        "type": "Point",
        "coordinates": [
          681244,
          4615079
        ]
      }
    }
```

**Comment by gimenete** [comment]
Sí, efectivamente era eso, era un typo. Muchas gracias!

Estaría muy bien que pudierais añadir ese link de about que comentas en tu último ejemplo.

Gracias de nuevo!

**Comment by virtor** [comment]
Acabamos de añadirlo, ya deberías poder verlo al obtener los datos de una línea

**Comment by gimenete** [comment]
Estupendo, ya lo veo. Muchas gracias!
