### ISSUE TITLE
Error en coordenadas wgs84

### ISSUE THREAD

**Issue by gimenete** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#41]
Hola,

Como comentaba en otro issue estamos migrando DNDzgz para usar el API en vez de escrapear páginas. He tenido un problema al pedir datos con coordenadas wgs84. Concretamente al pedir postes de una línea

```
http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/linea/${line}.json
```

Si lo pido como srsname=wgs84 los postes no quedan ubicados correctamente.

<img width="578" alt="screen shot 2016-05-31 at 22 18 01" src="https://cloud.githubusercontent.com/assets/50486/15702782/3e304e24-27e2-11e6-9520-0be3500bdb50.png">

La línea azul la obtengo de un KML de la página de urbanosdezaragoza. Como véis pasa por la calle perfectamente. Sin embargo las paradas están desplazadas.

Utilizando el formulario y el código de esta página (el código es de dominio público) http://home.hiwaay.net/~taylorc/toolbox/geography/geoutm.html si las pido en UTM y las traduzco yo a wgs84, obtengo resultados correctos (comprobado visualizándolos en el mapa). Os pongo un ejemplo:

UTM
678017.9803453928
4613320.634481554

Resultado con el código de esa web
-0.8621573182488046
41.65176128061068

Lo que devuelve el API
-0.8635188065232069
41.64990142803142

Hay una diferencia que a la hora de verlo en un mapa es significativa. Todavía no he comprobado otros endpoints, pero al menos el de buses tiene ese problema.

Gracias.

**Comment by virtor** [comment]
Hola, ya debería estar solucionado, hemos comprobado con http://geojsonlint.com que el contenido devuelto al hacer la petición

```
http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/linea/32.geojson?srsname=wgs84&rf=html
```

posiciona correctamente tanto los postes como el trazado de la línea, de no ser correcto nos lo dices.

Muchas gracias!

**Comment by gimenete** [comment]
Gracias!
