### ISSUE TITLE
¿Problemas con la publicación de la agenda cultural?

### ISSUE THREAD

**Issue by danilat** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#42]
Buenas,

Llevo cosa de una semana en la que no veo novedades en los eventos musicales/culturales de la fuente de datos que utilizo para la web y apps de http://www.mosica.es/. Parece que hay algún tipo de problema, ya que en la web del ayuntamiento sí aparecen.

Utilizo esta url  http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza.json?start=0&srsname=wgs84&rows=2000 y realizo una búsqueda en el JSON de respuesta para hacerme con los eventos musicales: Dentro de _result_, selecciono los eventos que tienen en _temas_ el _titie_ igual a _Música_. ¿Puede ser que no se estén publicando muchos eventos en ese endpoint?

**Comment by txtbits** [comment]
Buenos días,

Hemos revisado el endpoint con los eventos vigentes a día de hoy, filtrados a través de la temática Música, y creemos que es correcto.

La consulta que hemos utilizado es: 
[http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza.json?q=temas.id==16;diasParaTerminar=ge=0&start=0&rows=300](url)

El identificador de tema 16 corresponde con la temática Música.

¿Puedes indicarnos algún evento musical publicado en la web que no devuelva el endpoint?

Un saludo.

**Comment by danilat** [comment]
Tienes razón! Se publican todos los conciertos.

Pero he visto el problema que me estaba dando. Para los conciertos que importo necesito también la localización, y vengo usando la información dentro del elemento subEvent de cada evento. El tema es que por alguna razón la mayoría no lo tienen.

Te paso un ejemplo de evento de hoy mismo, de http://www.zaragoza.es/ciudad/actividades/detalle_Agenda?id=158785 el JSON que devuelve es

`{"id":158785,"title":"Sotos (Valencia)","description":"Compositor, guitarrista y cantante valenciano, en sus orígenes formo parte de grupos como La Instalación y Los Molestones, pero fue con su grupo La Rocka con quienes empezó a labrarse un nombre. Como La Rocka grabó dos álbumes y compartió escenario con grupos como Los Rodriguez, Danza Invisible y acompañó a Simple Minds en su gira española en el año 95. Después de unos años con La Rocka, Sotos se incorporó a la banda de Jaime Urrutia. Viene a pesentar su segundo disco en solitario \"Tiempo al Tiempo\", grabado en el verano del 2015 en los estudios CandyLand Rock.","destacada":false,"web":"http://sotosband.wix.com/sotosband" ,"poblacion":[{"id":6,"title":"Población en general"}],"festividadLocal":"N","barrerasArquit":"N","prepDiscapacidad":"N","precioEntrada":"<div>6 euros anticipada y 8 en taquilla</div>","startDate":"2016-06-02T00:00:00Z","endDate":"2016-06-02T00:00:00Z","alt":"http://www.zaragoza.es/ciudad/actividades/ficha_Agenda?codigo=158785","subtemas":[{"id":12,"title":"Pop/Rock","tema":{"id":16,"title":"Música","image":"//zaragoza.es/cont/paginas/actividades/imagen/musica.gif"}}],"temas":[{"id":16,"title":"Música","image":"//zaragoza.es/cont/paginas/actividades/imagen/musica.gif"}],"permanente":"N","lastUpdated":"2016-05-24T00:00:00Z","geometry":{"type":"Point","coordinates":[-0.8874190883447971,41.63876678308111]},"diasParaTerminar":-1}`

Por cierto, cambio la url a la que ataco para no traerme toooodos los eventos :)

**Comment by danilat** [comment]
Por cierto, otra cosa que sacaba del subEvent era la hora del evento

**Comment by txtbits** [comment]
Buenos días,

Existía un error y algunas actividades no mostraban correctamente la información relativa al lugar de realización. Ya está subsanado y devuelve correctamente todos los subEvent (lugares de realización) asociados a cada evento.

Para obtener los horarios tienes que obtenerlos directamente del subEvent, pero las fechas, las que se encuentran a nivel de evento son el rango de fechas máximo/mínimo. A pesar de que son muy pocos los casos, un evento puede tener diferentes lugares de realización en diferentes fechas. Si quieres obtener la duración máxima de la actividad, puedes utilizar estas y no tener que realizar ningún calculo adicional. En caso de que la actividad solo tenga un lugar de realización, las fechas coinciden.

Saludos y gracias por avisarnos.

**Comment by danilat** [comment]
Genial. Ya vuelvo a importar los datos perfectamente, muchas gracias Christian :)

**Comment by danilat** [comment]
Buenas! Estoy viendo que de nuevo me llegan datos sin el subEvent del que me traigo la localización de los eventos. 

Un saludo!

**Comment by txtbits** [comment]
Hola Daniel,
He realizado un ajuste, ahora la api debería devolver de nuevo los subevents de todas las actividades que tengan lugar de realización asociado. ¿Podrías confirmarme si los recuperas correctamente?

**Comment by danilat** [comment]
De los 34 elementos devueltos en http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza.json?start=0&srsname=wgs84&rows=5000&q=temas.id==16 10 vienen con subevent y 24 sin

**Comment by txtbits** [comment]
Buenos días,

Por un lado se ha subsanado un error que provocaba que algunas actividades no mostrarán el lugar de realización (subEvent) a pesar de tener uno o varios asociados y por tanto sus coordenadas georeferenciadas, sin embargo estas actividades si tenían coordenadas a nivel de actividad.

Por otro lado, debido a la diversidad de las actividades que se publican en la Sede Electrónica a través de la Agenda Zaragoza, existen actividades que son difíciles de georeferenciar ya que su localización es itinerante. Este mes debido a diferentes programaciones, el número de actividades que cumplía esta condición ha aumentado considerablemente, por lo que es problable que algunas de las actividades vigentes no tengan lugares de realización y por tanto estén georeferenciadas.

Estamos mejorando el sistema de publicación para subsanar estos casos, tanto para las actividades que en este momento están vigentes, como para que las actividades que se publiquen en un futuro.

Dejo abierto el hilo hasta que quede solucionado por completo.

Un saludo y gracias por notificarnos el problema.

**Comment by danilat** [comment]
Buenas Christian,

Veo desde hace un par de meses que no hay apenas contenido. Por lo que que visto no tiene relación con esto, es de contenido, pero no tengo muy claro a quien dirigirme para saber si la agenda se va a seguir manteniendo https://www.zaragoza.es/ciudad/actividades/listadoactos_Agenda?cod_tema=16&inc=50

**Comment by danilat** [comment]
Vaya, pues me he fijado hoy que vuelven a haber eventos, pero tengo problema por el formato, a muchos les falta el contenido de _subEvent_

**Comment by txtbits** [comment]
Hola de nuevo Daniel,

Tienes razón en lo que comentas, somos conscientes de que ha habido una reducción en el número de actividades que se publican en la Agenda Zaragoza, y además en algunas de las actividades publicadas falta información relacionada con el lugar de realización (subEvent).

Estamos trabajando para solucionarlo, además de resolver [lo que comentamos anteriormente](https://github.com/zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io/issues/42#issuecomment-229610353) en este mismo hilo.

Esperamos tener una solución lo antes posible y lo notificaremos por esta misma vía.

Un saludo y disculpa las molestias.
