### ISSUE TITLE
Endpoint de transporte urbano no devuelve datos

### ISSUE THREAD

**Issue by ender-null** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#44]
Básicamente devuelve `{"error":"Metodo no encontrado"}` todo el rato y lleva ya días o semanas, no recuerdo bien mientras que desde [http://www.urbanosdezaragoza.es/frm_esquemaparadatime.php?poste=](http://www.urbanosdezaragoza.es/frm_esquemaparadatime.php?poste=) se pueden obtener datos perfectamente, pero tener que scrappear la web no debería de ser la opción mas viable.

**Comment by francho** [comment]
El servicio también ha desaparecido del directorio de apis disponibles :-/

http://www.zaragoza.es/docs-api/

**Comment by ender-null** [comment]
Pues me he puesto a trabajar en una API REST de buses que scrappea datos de la web de Urbanos de Zaragoza, de momento se puede usar desde `https://api.drk.cat/zgzpls/bus?poste=<id>`, devuelve una lista de buses ordenados por tiempo, me he puesto a trabajar en ello hoy asi que aun hay algun bug y cosas por implementar. Pero con tal de tener un REST decente para mi aplicación me sirve.

PD: Si que está
![captura](https://cloud.githubusercontent.com/assets/11174915/20320014/a0f19218-ab70-11e6-878b-7fe7a28d09e0.PNG)

**Comment by virtor** [comment]
Tras solucionar problemas de comunicación con el servicio de acceso a tiempos de espera, ya debería funcionar el API de acceso a los tiempos de espera de los postes de autobús.

Disculpar las molestias.
