### ISSUE TITLE
Dataset de trámites y servicios en SOLR: Atributo descripción no disponible

### ISSUE THREAD

**Issue by ocorcho** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#45]
Estoy intentando hacer a los títulos y descripciones de los trámites y servicios publicados en el servicio SOLR, pero parece que el atributo description no está cargado para los trámites.

Se puede observar haciendo la siguiente llamada:
`https://www.zaragoza.es/buscador/select?q=*:*%20AND%20-tipocontenido_s:estatico%20AND%20category:Tr\u00e1mites&rows=800&fl=title,description`

Que es equivalente a los resultados obtenidos en
`https://www.zaragoza.es/buscador/select?q=*:*%20AND%20-tipocontenido_s:estatico%20AND%20category:Tr\u00e1mites&rows=800&fl=title`

**Comment by virtor** [comment]
Se puede obtener con esta uri (aunque el campo text tiene más contenido):
https://www.zaragoza.es/buscador/select?wt=json&q=*:*%20AND%20-tipocontenido_s:estatico%20AND%20category:Tr%5Cu00e1mites&rows=800&fl=title,text
