### ISSUE TITLE
Dataset de trámites y servicios. Exportación de HTML a markdown no funciona correctamente

### ISSUE THREAD

**Issue by ocorcho** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#46]
Con el siguiente comando:

`curl -X GET --header "Accept: text/csv" "https://www.zaragoza.es/sede/servicio/tramite?rf=markdown&results_only=false&rows=800&fl=id,title,descabre"`

Se debería obtener el campo de descabre (descripción abreviada) en markdown, siguiendo la nomenclatura habitual para especificar el formato en la salida. Sin embargo, los resultados siguen apareciendo en HTML en el campo descabre.

**Comment by virtor** [comment]
Corregido
