### ISSUE TITLE
Fallo de servicio en datos de transporte urbano

### ISSUE THREAD

**Issue by francho** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#47]
El servicio web de datos de frecuencia de buses ha dejado de funcionar. 

Urls que siempre han funcionado (por ejemplo http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/transporte-urbano/poste/tuzsa-392.json), ahora devuelven error de `{"error":"Parametros incorrectos"}`

**Comment by virtor** [comment]
Ya debería estar solucionado.


Disculpa las molestias
