### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by ender-null** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#48]
¿Que diferencias tiene la v2 de la API? ¿Hay que hacer algo en especial para usarla o usa los mismos endpoints que la v1?

**Comment by virtor** [comment]
La mayoría de los conjuntos de datos disponibles en la v1 están disponibles en la v2, el cambio más visible es la uri de acceso a los recursos, pero a nivel de atributos y operaciones disponibles se ha intentado mantener compatibilidad con la v1. 
La v1 se mantiene para no perjudicar los desarrollos existentes pero se recomienda migrar a la v2 ya que los nuevos conjuntos de datos se publicarán sobre ella.

**Comment by ender-null** [comment]
[https://www.zaragoza.es/sede/servicio/urbanismo-infraestructuras/transporte-urbano/poste-autobus/tuzsa-1169.json](https://www.zaragoza.es/sede/servicio/urbanismo-infraestructuras/transporte-urbano/poste-autobus/tuzsa-1169.json)
Seria un endpoint de la v2?

**Comment by virtor** [comment]
Sí, las uris de versión v2 son aquellas que cumplen https://www.zaragoza.es/sede/{conjunto-de-datos}

**Comment by ender-null** [comment]
Muchas gracias por todo ^^
