### ISSUE TITLE
API de buses fuera de servicio

### ISSUE THREAD

**Issue by ender-null** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#49]
[https://www.zaragoza.es/sede/servicio/urbanismo-infraestructuras/transporte-urbano/poste-autobus/tuzsa-1169.json](https://www.zaragoza.es/sede/servicio/urbanismo-infraestructuras/transporte-urbano/poste-autobus/tuzsa-1169.json)

`{"status":400,"mensaje":"; nested exception is: \n\tjava.net.SocketTimeoutException: Read timed out"}`

**Comment by virtor** [comment]
¿Sigue produciéndose el error? Lo hemos estado mirando y no lo hemos podido reproducir.

**Comment by ender-null** [comment]
Cuando lo abri llevaba casi todo el dia sin funcionar y luego medio funcionaba intermitentemente, pero parece que ya funciona.

**Comment by ender-null** [comment]
Se ha vuelto a caer la API con el mismo fallo, parece que sucede muy intermitentemente.
