### ISSUE TITLE
Subvenciones directas

### ISSUE THREAD

**Issue by runobe** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#5]
Me gustaría conocer las subvenciones que se adjudican de manera directa (sin previa convocatoria)
AT: Desde la operación del API para subvenciones se debe de poder filtrar por el atributo tipo_subvención con valor nominativa
AT: Se debe de plantear la consulta SPARQL que resuelva esta pregunta

**Comment by jrub** [comment]
Buenas, veo que estáis redactando issues como User Stories. Igual no soy el más indicado porque llevo unos años sin usar US's en proyectos... pero cosicas que veo a mejorar:
- Se suele especificar un sujeto: "**Como ciudadano**, me gustaría conocer las subvenciones...". Otras podrían ser "Como administrador del portal...", "Como reutilizador...", "Como asociación que da de alta datos en el sistema..." (probablemente haya un nombre mejor para esto XD) ; y habría que evitar generalidades: "Como usuario..."
- Los ATs los veo muy técnicos, ¿no? creo que deberían permitir que el Product Owner (que puede ser el cliente o un perfil intermediario no técnico, normalmente) valide la US.

A ver si puedo liar a alguien más puesto en redactar US para que eche un vistazo (y así evitar ambiguedades y otros problemas que surgen luego) :-) ¡Ánimo con lo que estáis haciendo, y a por todas!

**Comment by laurafl** [comment]
```
PREFIX essubv: <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/subvencion#>
PREFIX espresu:<http://vocab.linkeddata.es/datosabiertos/def/hacienda/presupuesto#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX s:<http://schema.org/>
select distinct ?uri ?titulo ?fechaInicio ?fechaFin ?año ?porcentajeAnticipado ?presupuesto ?funcion ?gestor ?ambito ?estrategia ?esMultianual ?objeto
where {
?uri a essubv:Convocatoria;
         dcterms:title ?titulo;
         s:startDate ?fechaInicio;
         s:endDate ?fechaFin;
         espresu:año ?año;
         espresu:porcentajeAnticipado ?porcentajeAnticipado;
         espresu:presupuesto ?presupuesto;
         essubv:funcion/dcterms:title ?funcion;
         essubv:gestor/dcterms:title ?gestor;
         essubv:lineaAmbito/dcterms:title ?ambito;
         essubv:lineaEstrategica/skos:narrower/dcterms:title ?estrategia;
         essubv:multianual ?esMultianual;
         essubv:objeto/dcterms:title ?objeto;
         essubv:tipo/dcterms:identifier "3".
}
```

**Comment by jrub** [comment]
El filtro por `tipo_subvencion` que comenta el primer AT, ¿es este?: `essubv:tipo/dcterms:identifier "3".`

Si es así, ¿qué representa el "3"?

He intentado buscar en los vocabularios para ver si lo entendía. El primero http://vocab.linkeddata.es/datosabiertos/def/hacienda/presupuestos da **404**. En el segundo no lo he encontrado o bien me cuesta todavía interpretar bien estos vocabularios. Además, también hay tipos no disponibles: http://vocab.linkeddata.es/page/datosabiertos/kos/hacienda/presupuestos/tipoGastoFuncional

**Comment by laurafl** [comment]
Exacto, el 3 representa el tipo de subvención. Para conocer los tipos de subvenciones existentes puedes hacer esta consulta:

```
PREFIX essubv: <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/subvencion#>
PREFIX espresu:<http://vocab.linkeddata.es/datosabiertos/def/hacienda/presupuestos#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX s:<http://schema.org/>
select distinct ?tipo ?nombre
where {
?uri a essubv:Convocatoria;
essubv:tipo/dcterms:identifier ?tipo;
essubv:tipo/dcterms:title ?nombre.
}
```

Como puedes ver hay dos: "Concurrencia Competitiva" y "Subvenciones previstas nominativamente en el Presupuesto General del Ayuntamiento"
La segunda parte de lo que preguntas respecto a los vocabularios lo miramos.

**Comment by ocorcho** [comment]
Los problemas de redirección los arreglaré en breve. 

Ahora es: `http://vocab.linkeddata.es/datosabiertos/def/hacienda/presupuesto`, porque hemos tenido que cambiar a singular. En cualquier caso tengo que darle un repaso en breve.
