### ISSUE TITLE
Mejor ordenacion de las facturas en la web

### ISSUE THREAD

**Issue by mingodad** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#51]
Hola !
Parece que por defecto en la web https://www.zaragoza.es/ciudad/encasa/hacienda/buscador_Facturas?&cuantia=&ejercicio=&gestor=&proveedor=&signo=&desc=&control=&inc=10&numpag=0 las facturas vienen ordenadas por importe decreciente y pienso que seria mejor ordenarlas por fecha_pago decreciente asi la primera pagina presentaria las ultimas facturas entradas en el sistema.

**Comment by runobe** [comment]
Se ha generado un nuevo servicio de visualización y ha contemplado esta petición
