### ISSUE TITLE
Falta parada en la API de buses

### ISSUE THREAD

**Issue by ender-null** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#52]
Acabo de notar que al consultar esta parada da error:
https://zaragoza.es/sede/servicio/urbanismo-infraestructuras/transporte-urbano/poste-autobus/tuzsa-1249.json
Pero en la web si que tienen los datos:
http://zaragoza.avanzagrupo.com/frm_esquemaparadatime.php?poste=1249

**Comment by virtor** [comment]
Acabamos de actualizar los datos de paradas y la que comentas ya funciona.

Gracias por el aviso y disculpas.

**Comment by ender-null** [comment]
Muchas gracias ^^
