### ISSUE TITLE
Api Locales Vacíos: Url de foto incorrecta para local 963

### ISSUE THREAD

**Issue by francho** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#53]
La url de foto que devuelve para el local con id 963 (Avenida América 28) no es una URL válida ya que contiene un espacio

```
https://www.zaragoza.es/sede/servicio/locales-vacios/963.json?rf=html&srsname=utm30n&fl=photos

{"photos":[{"uri":"/cont/locales-vacios/2/AMERICA 28.jpg"}]}
```

**Comment by virtor** [comment]
Acabamos de corregir el tratamiento para los nombres de fichero.

**Comment by francho** [comment]
Ok ya veo, aunque creo que para este caso sería mejor renombrar también la foto ya que los espacios en las urls pueden dar problemas de parseo (dependiendo de la librería) aunque estén escapados
