### ISSUE TITLE
Api Locales Vacíos: problemas con el orden por defecto y la paginación

### ISSUE THREAD

**Issue by francho** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#54]
Cuando se piden datos de locales paginandos (usando los parámetros `start` y `rows`) aparecen datos duplicados en las sucesivas consultas y no se corresponden con los mostrados en la misma consulta sin paginar.

Adjunto Ejemplos de respuesta para ilustrarlo
[locales-vacios_all.txt](https://github.com/zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io/files/1230995/locales-vacios_all.txt)
[locales-vacios_paginated.txt](https://github.com/zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io/files/1230996/locales-vacios_paginated.txt)

**Comment by virtor** [comment]
Acabamos de modificar la ordenación de los resultados y ya no debería producirse el problema de la no correspondencia al paginar.
