### ISSUE TITLE
Api Locales Vacíos: documentación servicio de fotos de local

### ISSUE THREAD

**Issue by francho** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#55]
Con la documentación actual es imposible poder usar el servicio de fotos ya que no se sabe que parámetros hay que usar para obtener las fotos de un local.

Incluso con el [formulario de la documentación](https://www.zaragoza.es/docs-api_sede/#!/Urbanismo%3A_Locales_vacios/get_servicio_locales_vacios_fotos)  es imposible y devuelve un error 400

**Comment by virtor** [comment]
El servicio de fotos estará corregido mañana, de todas formas puede acceder a las fotos a través del detalle de un local, ya que hemos corregido las uris para que sean absolutas, por ejemplo:

https://www.zaragoza.es/sede/servicio/locales-vacios/1202.json

**Comment by virtor** [comment]
También puedes obtener las fotos a través de una petición como la siguiente:

https://www.zaragoza.es/sede/servicio/locales-vacios/1202.json?fl=photos
