### ISSUE TITLE
Fechas en el calendario de eventos musicales 1 día mal

### ISSUE THREAD

**Issue by danilat** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#57]
Hola,

Pensaba que eran errores puntuales pero he estado viendo que es un error que pasa en todos o casi todos los conciertos publicados a través del API, pero están mal por 1 día de diferencia. Esta es la llamada que hago http://www.zaragoza.es/api/recurso/cultura-ocio/evento-zaragoza.json?start=0&srsname=wgs84&rows=5000&q=temas.id==16

Algunos ejemplos: 

- Con el id 177776 en ese JSON el concierto de Rapsusklei lo marca el 13 cuando en realidad es el 14 https://www.zaragoza.es/sede/portal/cultura/fiestas-pilar/servicio/cultura/evento/177776 

- El de Kase O, con 171926 http://www.zaragoza.es/ciudad/actividades/ficha_Agenda?codigo=171926

- El de El Brindador con id 178762 http://www.zaragoza.es/ciudad/actividades/ficha_Agenda?codigo=178762

**Comment by virtor** [comment]
Hola, el día se almacena como datetime en formato GMT y por esto puede parecer erróneo ya que en el sistema de información se guarda el día y la hora a 00:00h.

En España ahora estamos en GMT+2 por lo que al dato que se obtiene en el json hay que sumarle 2 horas lo que da como resultado el día siguiente. 

Es una transformación que utilizando librerías de tratamiento de fechas debería hacerse de forma automática.

Por ejemplo "2017-10-13T22:00:00Z" equivale en España al 14-10-2017 a las 00:00
```java
java.text.DateFormat df = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
df.setTimeZone(java.util.TimeZone.getTimeZone("Zulu"));
java.util.Date date = df.parse("2017-10-13T22:00:00Z");
System.out.println(date.toString());
```

Al ejecutarlo devuelve

```
Sat Oct 14 00:00:00 CEST 2017
```
