### ISSUE TITLE
Ayuda para crear una consulta que devuelva las actividades en un día en concreto

### ISSUE THREAD

**Issue by afleta** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#59]
Hola, 

estoy intentando hacer una consulta de las actividades para un día en concreto, es decir, algo parecido a GET /servicio/actividades/evento/hoy pero para un día en concreto.

Desde mi poca experiencia en FIQL, había pensado la siguiente consulta:

https://www.zaragoza.es/sede/servicio/actividades/evento/list?rf=markdown&srsname=utm30n&rows=50&q=startDate=lt=2019-02-07;endDate=ge=2019-02-07;subEvent.openingHours.dayOfWeek==Jueves

pero da el siguiente error:

org.apache.cxf.jaxrs.ext.search.PropertyNotFoundException

También he hecho la siguiente consulta:

https://www.zaragoza.es/sede/servicio/actividades/evento/list?rf=markdown&srsname=utm30n&rows=50&q=startDate=lt=2019-02-07;endDate=ge=2019-02-07

y luego filtrar con linq subEvent.openingHours.dayOfWeek, pero no es óptimo. ¿Existe alguna consulta para lo que busco?

Muchas gracias

**Comment by virtor** [comment]
Hola, la petición para obtener los actos de un día la acabamos de hacer pública, los datos se obtendrían por ejemplo:

https://www.zaragoza.es/sede/servicio/cultura/evento/calendar.json?startDate=07-02-2019

Reciba un cordial saludo y si la respuesta soluciona su duda, por favor, cierre la issue.
