### ISSUE TITLE
Es posible que no funcione la API de Bizi Zaragoza?

### ISSUE THREAD

**Issue by shadowzgz** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#63]
He estado usando el API de Zaragoza respecto al estacionamiento Bizi, pero desde ayer sobre las 20:00 dejó de funcionar. En el siguiente enlace se puede comprobar que no se reciben los datos de las estaciones.
https://www.zaragoza.es/sede/servicio/urbanismo-infraestructuras/estacion-bicicleta?rf=html&srsname=wgs84&start=0&rows=50&distance=500

En JSON esto es lo que devuelve.

`{"totalCount":0,"start":0,"rows":50}`

Por lo que he podido comprobar, el resto de aplicaciones que usan esta API, como las de Android están paradas y sin actualizar datos. Espero que se solucione pronto.

Un saludo.

**Comment by shadowzgz** [comment]
Hola, actualizo para comentar que ya funciona.

**Comment by runobe** [comment]
Hola, creo que el servicio vuelve a funcionar en el ejemplo que nos indicas ya devuelve resultados
{"totalCount":130,"start":0,"rows":50}

**Comment by carrilesbici** [comment]
Hola, parece que vuelve a estar caida, tocara esperar a que lenvanten el servicio de nuevo :P

**Comment by ekzGuille** [comment]
Efectivamente sigue caída.
