### ISSUE TITLE
No devuelve los tiempos del tranvía

### ISSUE THREAD

**Issue by JaviGoni** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#64]
Ninguna parada del tranvía esta devolviendo los tiempos de espera del tranvia ya que no se actualiza desde el día 1 de Marzo

http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/tranvia/101.json

**Comment by Jorkoh** [comment]
¿Alguna novedad? Me canso de responder correos y reviews intentando explicar por qué llevamos 10 días sin poder ver los tiempos del tranvía.

**Comment by runobe** [comment]
La incidencia fue comunicada a la empresa concesionaria desde el 4 de marzo

**Comment by virtor** [comment]
Se ha restablecido el acceso a los datos del tranvía
