### ISSUE TITLE
Alertas del tranvía con errores

### ISSUE THREAD

**Issue by JaviGoni** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#67]
Podéis revisar los literales devueltos en las alertas de las paradas del Tranvía? 
Se omiten caracteres

![Sin título](https://user-images.githubusercontent.com/43927296/129441118-364cfc4d-2945-4dc3-8855-6bf4cb97c149.png)

**Comment by JaviGoni** [comment]
Alguna novedad?

**Comment by virtor** [comment]
Hola, ¿puedes mirar si ya aparecen los caracteres? 

Saludos y disculpa la tardanza

**Comment by JaviGoni** [comment]
Hola, si, veo que la palabra "tranva" se ha corregido y ya se recibe bien

Si veo más palabras mal escritas, reabro

Un saludo y muchas gracias!
