### ISSUE TITLE
No duelve los tiempos del tranvía

### ISSUE THREAD

**Issue by JaviGoni** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#68]
Ninguna parada del tranvía esta devolviendo los tiempos de espera del tranvia ya que no se actualizan los datos desde el día 4 de Abril a las 10:12am

http://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/tranvia/101.json

**Comment by virtor** [comment]
Hola, nos comentan que se están haciendo tareas de mantenimiento de los sistemas y que se espera que la red vuelva a estar operativa durante mañana 7 de abril.

Disculpa las molestias

**Comment by JaviGoni** [comment]
Gracias por la info @virtor

Hay alguna forma de que nos podamos enterar sin tener que abrir una issue? Más que nada porque tener a los usuarios 3 días sin poder buscar un solo tranvía y no poder informarles nos penaliza mucho

**Comment by JaviGoni** [comment]
1 semana después, siguen llegando datos del día 4, alguna novedad?

**Comment by JaviGoni** [comment]
Hola @virtor, llevamos camino de 3 semanas sin servicio, varios usuarios me están mandando emails preguntando que ocurre, hay alguna novedad? Los datos siguen marcando el día 04/04

**Comment by virtor** [comment]
Hola, lo único que sabemos es que están trabajando en solucionar el error, en cuanto lo hagan te aviso.

Saludos y disculpa las molestias

**Comment by virtor** [comment]
Hola, nos comentan que ya se ha restablecido la conectividad.

Saludos
