### ISSUE TITLE
No funciona el servicio de información de una estación Bizi

### ISSUE THREAD

**Issue by DavidAsin** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#69]
El servicio no funciona:

https://www.zaragoza.es/sede/servicio/urbanismo-infraestructuras/estacion-bicicleta/130?rf=html&srsname=wgs84

devuelve:

{
"status": 400,
"mensaje": "Index: 0, Size: 0"
}

**Comment by virtor** [comment]
Hola, puedes probar a acceder ahora?

Saludos y disculpa las molestias

**Comment by DavidAsin** [comment]
Ya funciona, muchas gracias!

**Comment by DavidAsin** [comment]
@virtor vuelve a fallar por el mismo motivo

**Comment by virtor** [comment]
Puedes volver a probar?

**Comment by DavidAsin** [comment]
vuelve a funcionar, gracias!
