### ISSUE TITLE
Subvenciones por Beneficiario

### ISSUE THREAD

**Issue by runobe** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#7]
Me gustaría conocer el detalle de todas las subvenciones que ha recibido un beneficiario
AT: Desde las operación del API para subvenciones se deberá poder filtrar por el atributo beneficiario
AT:Se debe de plantear una consulta SPARQL que resuelva esta pregunta

**Comment by laurafl** [comment]
Primero podemos obtener un listado de ayudas y subvenciones via API
http://www.zaragoza.es/api/recurso/sector-publico/ayuda-subvencion.json

El beneficiario se detalla en los campos beneficiario e idBeneficiario por lo que si queremos obtener las subvenciones concedidas a "A.M.P.A. INSTITUTO DE EDUCACION SECUNDARIA PILAR LORENGAR" cuyo id es el 112 la consulta via API sería
http://www.zaragoza.es/api/recurso/sector-publico/ayuda-subvencion.json?q=idBeneficiario==112

**Comment by laurafl** [comment]
PREFIX essubv: http://vocab.linkeddata.es/datosabiertos/def/sector-publico/subvencion#
PREFIX espresu: http://vocab.linkeddata.es/datosabiertos/def/hacienda/presupuestos#
PREFIX dcterms: http://purl.org/dc/terms/
PREFIX skos: http://www.w3.org/2004/02/skos/core#
PREFIX s:http://schema.org/
select distinct ?uri ?titulo ?beneficiario ?importeSolicitado ?importeConcedido ?convocatoria ?nombreGestor
where {
?uri a essubv:Resolucion;
         essubv:convocatoria ?convocatoria;
         dcterms:title ?titulo;  
         essubv:importeSolicitado ?importeSolicitado;
         essubv:creditoPresupuestoInicial ?importeConcedido;
         essubv:adjudicatario/s:name ?beneficiario.
?convocatoria essubv:gestor/dcterms:title ?nombreGestor.
FILTER (regex(?beneficiario, "ASOCIACIÓN TALLER EDUCATIVO-LABORAL", "i"))}
