### ISSUE TITLE
Problema en mensajes de alerta del tranvía

### ISSUE THREAD

**Issue by JaviGoni** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#71]
Esta siendo imposible hacer un decode del json que estáis enviando ya que estáis enviando una alerta en la API del tranvía entre "" como se puede ver en la captura y hace que no funcione ninguna app

![Captura de Pantalla 2022-10-08 a las 10 37 32](https://user-images.githubusercontent.com/43927296/194698427-7b2e4293-923a-4372-9c43-00d8a980669d.png)

**Comment by virtor** [comment]
Hola, ¿os sigue pasando? Puedes enviarnos la petición que hacéiss? en la información que se muestra ahora parece que está corregido

Saludos y disculpa las molestias

**Comment by JaviGoni** [comment]
Si lanzas el endpoint se puede ver el problema
https://www.zaragoza.es/api/recurso/urbanismo-infraestructuras/tranvia/101.json

**Comment by virtor** [comment]
¿Puedes comprobar si ahora funciona correctamente?

**Comment by JaviGoni** [comment]
Ya están funcionando de nuevo las apps, no se si habrá algun mensaje más que pueda dar algún problema

gracias @virtor
