### ISSUE TITLE
No funcionan los endpoints del Tranvía y Bizi

### ISSUE THREAD

**Issue by JaviGoni** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#72]
Hola, han dejado de funcionar los endpoits del tranvía y del servicio de Bizi, ocurre algo?

**Comment by virtor** [comment]
Hola, nos puedes indicar las peticiones que dan error? Hemos probado y parece que ahora funcionan correctamente

**Comment by JaviGoni** [comment]
Nada, ayer por la tarde ya volvía a funcionar con normalidad
