### ISSUE TITLE
Incoherencias entre categorías de buscador avanzado y temas_smultiple

### ISSUE THREAD

**Issue by n3b0r** [zaragoza-sedeelectronica/zaragoza-sedeelectronica.github.io#8]
Cuando se realiza una búsqueda avanzada a través de http://www.zaragoza.es/ciudad/actividades/buscar_Agenda existen una serie de temáticas diferentes a las devueltas a través de petición vía API.

Ejemplo, la temática "Tecnología y Ciudadanía" es devuelta vía API pero esta no existe como filtro en el buscador avanzado.

Por otro lado, ¿es posible encontrar en algún sitio el listado de temáticas disponibles?

Gracias y un saludo

**Comment by virtor** [comment]
Hemos añadido la temática "Tecnología y Ciudadanía" al buscador que indicas, para obtener el listado de temáticas existentes lo puedes hacer vía petición al api:

`http://www.zaragoza.es/api/recurso/cultura-ocio/tema/evento-zaragoza{.json|.xml...}`

Si quieres obtener las temáticas que tienen actividades **vigentes** lo puedes vía punto SPARQL http://datos.zaragoza.es/sparql y ejecutar la siguiente consulta:

`PREFIX acto:<http://vocab.linkeddata.es/datosabiertos/def/cultura-ocio/agenda#>
SELECT DISTINCT ?id ?nombre WHERE {
  ?uriCont a acto:Evento.   
  ?uriCont skos:broader ?tema.
  ?tema skos:notation ?id.
  ?tema skos:prefLabel ?nombre.
}`

Saludos
